const Rings = {
  0: 'Friendship Ring',
  1: 'Power Ring L-1',
  2: 'Power Ring L-2',
  3: 'Power Ring L-3',
  4: 'Armor Ring L-1',
  5: 'Armor Ring L-2',
  6: 'Armor Ring L-3',
  7: 'Red Ring',
  8: 'Blue Ring',
  9: 'Green Ring',
  10: 'Cursed Ring',
  11: 'Expert\'s Ring',
  12: 'Blast Ring',
  13: 'Rang Ring L-1',
  14: 'GBA Time Ring',
  15: 'Maple\'s Ring',
  16: 'Steadfast Ring',
  17: 'Pegasus Ring',
  18: 'Toss Ring',
  19: 'Heart Ring L-1',
  20: 'Heart Ring L-2',
  21: 'Swimmer\'s Ring',
  22: 'Charge Ring',
  23: 'Light Ring L-1',
  24: 'Light Ring L-2',
  25: 'Bomber\'s Ring',
  26: 'Green Luck Ring',
  27: 'Blue Luck Ring',
  28: 'Gold Luck Ring',
  29: 'Red Luck Ring',
  30: 'Green Holy Ring',
  31: 'Blue Holy Ring',
  32: 'Red Holy Ring',
  33: 'Snowshoe Ring',
  34: 'Roc\'s Ring',
  35: 'Quicksand Ring',
  36: 'Red Joy Ring',
  37: 'Blue Joy Ring',
  38: 'Gold Joy Ring',
  39: 'Green Joy Ring',
  40: 'Discovery Ring',
  41: 'Rang Ring L-2',
  42: 'Octo Ring',
  43: 'Moblin Ring',
  44: 'Like Like Ring',
  45: 'Subrosian Ring',
  46: 'First Gen Ring',
  47: 'Spin Ring',
  48: 'Bombproof Ring',
  49: 'Energy Ring',
  50: 'Dbl. Edge Ring',
  51: 'GBA Nature Ring',
  52: 'Slayer\'s Ring',
  53: 'Rupee Ring',
  54: 'Victory Ring',
  55: 'Sign Ring',
  56: '100th Ring',
  57: 'Whisp Ring',
  58: 'Gasha Ring',
  59: 'Peace Ring',
  60: 'Zora Ring',
  61: 'Fist Ring',
  62: 'Whimsical Ring',
  63: 'Protection Ring',
};

const Games = {
  0: 'Ages',
  1: 'Seasons',
};

const Animals = {
  3: 'Ricky',
  4: 'Dimitri',
  5: 'Moosh',
}

const ChildBehaviors = {
  0:  'Infant',
  1:  'BouncyA',
  2:  'BouncyB',
  3:  'BouncyC',
  4:  'BouncyD',
  5:  'BouncyE',
  6:  'ShyA',
  7:  'ShyB',
  8:  'ShyC',
  9:  'ShyD',
  10: 'ShyE',
  11: 'HyperA',
  12: 'HyperB',
  13: 'HyperC',
  14: 'HyperD',
  15: 'HyperE',
};



export {
  Rings,
  Games,
  Animals,
  ChildBehaviors,
};
